spring:
  datasource:
    url: jdbc:mysql://172.29.85.38:3306/code
    username: root
    password: Root_123#@!
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
    default-fetch-size: 100
  mapper-locations: classpath*:mapper/*Mapper*.xml